Nominal/One Hot Encoding Technique

Basically we try to convert a categorical feature to numerical feature. That's called encoding.

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
# Create a dataframe
df = pd.DataFrame({
  'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
# Create an instance of OneHotEncoder
encoder = OneHotEncoder()

In [6]:
# Perform fit and transform
encoder.fit_transform(df[['color']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [8]:
encoded = encoder.fit_transform(df[['color']]).toarray()

In [10]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [11]:
pd.concat([df, encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0