Nominal/One Hot Encoding Technique

Basically we try to convert a categorical feature to numerical feature. That's called encoding.

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
# Create a dataframe
df = pd.DataFrame({
  'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
# Create an instance of OneHotEncoder
encoder = OneHotEncoder()

In [5]:
# Perform fit and transform
encoder.fit_transform(df[['color']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [6]:
encoded = encoder.fit_transform(df[['color']]).toarray()

In [7]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [8]:
pd.concat([df, encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [9]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

Label Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder

lbl_encoder = LabelEncoder()

In [11]:
lbl_encoder.fit_transform(df[ ['color'] ])

d:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [12]:
lbl_encoder.transform([['red']])

d:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [13]:
lbl_encoder.transform([['green']])

d:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [14]:
lbl_encoder.transform([['blue']])

d:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

Ordinal Encoding:

It is used to encode categorical data that have an intrinsic order or ranking.

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
# Create a small dataframe
df = pd.DataFrame({
  'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [17]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [21]:
# Create an instance of OrdinalEncoder and then fit_transform
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [22]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

Target Guided Ordinal Encoding

Here, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category.

In [23]:
# Create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
  'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
  'price': [200, 150, 300, 250, 180, 320]
})

In [24]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [25]:
mean_price = df.groupby('city')['price'].mean()

In [26]:
mean_price

city
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64

In [28]:
# Convert to dictionary
mean_price.to_dict()

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [29]:
df['city_encoded'] = df['city'].map(mean_price)

In [30]:
df[['price', 'city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0